#!/bin/sh
# To enable this hook, put this file in .git/hooks/.

(
    REASON="`git push 2>&1`"
    if [ $? != 0 ]; then
        notify-send \
            "Failed: git push" \
            "Failed to push to \"$PWD\":\n$REASON" \
            -c "transfer.error" \
            --icon=dialog-error
    else
        notify-send \
            "Completed: git push" \
            "Pushed changes to \"$PWD\"." \
            -c "transfer.complete" \
            --icon=dialog-information
    fi
)&

